USE master 
GO 

IF DB_ID('BD_MAQUINARIAS') IS NOT 
NULL DROP DATABASE BD_MAQUINARIAS 
GO
CREATE DATABASE BD_MAQUINARIAS 
ON PRIMARY(
	NAME='BD_MAQUINARIAS_PRI',
	FILENAME='C:\MAQUINARIAS\DATA\BD_MAQUINARIAS.MDF',
	SIZE=10,
	MAXSIZE=100,
	FILEGROWTH=10%),
( 
	NAME='BD_MAQUINARIAS_SEC',
	FILENAME='C:\MAQUINARIAS\DATA\BD_MAQUINARIAS.NDF',
	SIZE=5,
	MAXSIZE=50,
	FILEGROWTH=10% 
)
LOG ON (
	NAME='BD_MAQUINARIAS_TRA',
	FILENAME='C:\MAQUINARIAS\DATA\BD_MAQUINARIAS.LDF',
	SIZE=5,
	MAXSIZE=40,
	FILEGROWTH=10% 
) 
GO 


--Verificando los archivos creados en la base de datos BD_MAQUINARIAS 
--SP_HELPDB BD_MAQUINARIAS 
--GO 

/* 1. Al archivo de transacciones: Ampliar el tamaño inicial del archivo de transacciones a 10MB. Modificar la tasa de crecimiento en un 15%. */
ALTER DATABASE BD_MAQUINARIAS
	MODIFY FILE
	(NAME='BD_MAQUINARIAS_TRA',
	SIZE=10,
	FILEGROWTH=15% 
	) 
GO 

/* 2. Agregar archivos: Agregar tres archivos secundarios llamados BD_MAQUINARIAS1, BD_MAQUINARIAS2
y BD_MAQUINARIAS3 de tamaño inicial 5MB y máximo tamaño 20MB, los cuales
estarán ubicados en C:\MAQUINARIAS\SEC. */ 
ALTER DATABASE BD_MAQUINARIAS
	ADD FILE ( 
	NAME='BD_MAQUINARIAS1',
	FILENAME='C:\MAQUINARIAS\SEC\BD_MAQUINARIAS1.NDF',
	SIZE=5,
	MAXSIZE=20,
	FILEGROWTH=10%)
GO  

ALTER DATABASE BD_MAQUINARIAS
	ADD FILE ( 
	NAME='BD_MAQUINARIAS2',
	FILENAME='C:\MAQUINARIAS\SEC\BD_MAQUINARIAS2.NDF',
	SIZE=5,
	MAXSIZE=20,
	FILEGROWTH=10%)
GO  

ALTER DATABASE BD_MAQUINARIAS
	ADD FILE ( 
	NAME='BD_MAQUINARIAS3',
	FILENAME='C:\MAQUINARIAS\SEC\BD_MAQUINARIAS3.NDF',
	SIZE=5,
	MAXSIZE=20,
	FILEGROWTH=10%)
GO  


/* 3. Eliminar archivos: Eliminar el archivo BD_MAQUINARIAS2. */
ALTER DATABASE BD_MAQUINARIAS
REMOVE FILE BD_MAQUINARIAS2
GO 


SP_HELPDB BD_MAQUINARIAS 
GO 