CREATE DATABASE bb_ventas;
GO

USE bb_ventas;

CREATE TABLE PRODUCTO (
ID_PRODUCTO CHAR(6) NOT NULL,
DESCRIPCIO VARCHAR(50),
PRECIO_VENTA MONEY ,
STOCK_MIN INT,
STOCK_ACTUAL INT,
FECHA_VENCIMIENTO DATE,
PRIMARY KEY (ID_PRODUCTO)
);
GO

ALTER TABLE PRODUCTO
ADD STCK_MAX INT;
GO

ALTER TABLE PRODUCTO
ADD PRE_COSTO MONEY,
UNI_MEDIDA VARCHAR(25),
COD_CATE CHAR(3)
GO

CREATE TABLE CATEGORIAS(
COD_CATE CHAR(3),
NOMBRE VARCHAR(100),
PRIMARY KEY (COD_CATE)
)
GO

ALTER TABLE PRODUCTO
ADD FOREIGN KEY (COD_CATE) REFERENCES CATEGORIAS
GO